apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" .Values.name .Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: cie-bootcamp.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.name}}
            port:
              number: 80
